### ISSUE TITLE
开启rowSelection={{}}后批量删除不可用，点击一行就会全选所有行，且传入的record是空的

### ISSUE THREAD

**Issue by Dephie** [jaykou25/react-admin-kit#21]
![image](https://github.com/jaykou25/react-admin-kit/assets/128899536/6ac7bf9b-4763-4289-ad9d-ca01875bc171)
![image](https://github.com/jaykou25/react-admin-kit/assets/128899536/3c78cbf5-ffb1-4c58-beda-73b0c38e7398)

**Comment by jaykou25** [comment]
应该是 dataSource 里没有 id 导致的，或者 id 不唯一。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dephie ***@***.***&gt;
发送时间: 2024年5月30日 22:12
收件人: jaykou25/react-admin-kit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jaykou25/react-admin-kit] 开启rowSelection={{}}后批量删除不可用，点击一行就会全选所有行，且传入的record是空的 (Issue #21)





 
image.png (view on web)
 image.png (view on web)

**Comment by jaykou25** [comment]
PorTable 有一个属性 rowKey 用来指定一个字段，它的取值必须是唯一的，默认取值是 id;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dephie ***@***.***&gt;
发送时间: 2024年5月30日 22:12
收件人: jaykou25/react-admin-kit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [jaykou25/react-admin-kit] 开启rowSelection={{}}后批量删除不可用，点击一行就会全选所有行，且传入的record是空的 (Issue #21)





 
image.png (view on web)
 image.png (view on web)
