### ISSUE TITLE
columns里的actionRef不可用

### ISSUE THREAD

**Issue by Dephie** [jaykou25/react-admin-kit#22]
columns里的render函数的参数actionRef不可用，如果我想要在表格其中一列点击按钮后就可以向服务端发送请求并且刷新表格应该怎么做呢?（点击开始采集和暂停采集就可以更新采集状态的一栏的值）
![image](https://github.com/jaykou25/react-admin-kit/assets/128899536/70fabab8-261e-47ed-92f0-79c872d20a6f)
点击按钮后显示actionRef.current为undefined。
![image](https://github.com/jaykou25/react-admin-kit/assets/128899536/9682c1e1-fd23-44e7-b400-716f3c6f922f)

**Comment by jaykou25** [comment]
现在只有 valueType 为 `option` 的列中的 render 函数才会有 actionRef. 其它列的 render 函数里并没有这个 ref.

不过虽然其它的列中没有这个 ref, 你仍然可以把 actionRef 作为属性传给它.

```js
// 页面
const Demo = () => {
  const actionRef = useRef()

  return <ProTable 
               actionRef={actionRef} 
               columns={getColumns(actionRef)} // 作为属性传入
              />
}
```

```js
// columns 函数
export const getColumns = (actionRef) => {
  return [
    {
      title: '采集任务状态',
      dataIndex: 'status',
      render: () => {
         return <Button onClick={() => actionRef.current?.reload()}>暂停</Button>
      }
    }
 ]
}
```
