### ISSUE TITLE
查询表单之间有联动，columns如何实现

### ISSUE THREAD

**Issue by xiumubai** [jaykou25/react-admin-kit#23]
我的查询表单之间有联动，上一个组件改动值以后，下一个组件的状态也会跟着变化，或者显示隐藏，这种能实现吗？

**Comment by jaykou25** [comment]
报歉, 这是一个 bug, 理论是可以的, 查询表单也是由 SchemaForm 生成的, 应该是可以通过 dependency 或 formInstance 赋值来实现的. 晚些时候我会发一个版本来修复, 并在文档中添加一个示例.

**Comment by jaykou25** [comment]
你好, 我发布了 v0.5.3, 并更新了文档, 添加了一个[示例](https://jaykou25.github.io/react-admin-kit/components/pro-table#%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95%E7%9A%84%E5%85%B3%E8%81%94%E6%8E%A7%E5%88%B6). 

但是还是有一个小问题, 就是隐藏项的占位还在. 这是 pro-component 的一个 bug, 我会给他们反馈这个问题.

**Comment by xiumubai** [comment]
非常感谢，我能用你的这个组件库改造一下用在自己的项目上吗？

**Comment by jaykou25** [comment]
可以啊, 开源的项目你随便改造, fork 一个项目分支就行. 如果有比较共通的需求, 也可以提 pull-request 来贡献这个项目.

**Comment by jaykou25** [comment]
ProTable 的搜索表单区域底层用的是 [QueryFilter 组件](https://procomponents.ant.design/components/query-filter).

1. 从需求层面来说, 搜索表单在设计之初就希望每一个搜索项都应该让用户看到, 所以不支持显示/隐藏的控制. 但是可以控制表单项的禁用/启用状态.
2. 从源码层面来说, 每一个表单项都包了一个 Col  组件, 即使是 dependency 组件返回的是空也会被包上 Col  组件, 这就导致了虽然组件为空但是占位还在. 这一块改动会比较麻烦, 所以在 **搜索表单** 中最佳的实践是 dependency 组件中只返回一个表单项, 不要做显示/隐藏的控制.

我重新更新了这个 [示例](https://jaykou25.github.io/react-admin-kit/components/pro-table#%E6%90%9C%E7%B4%A2%E8%A1%A8%E5%8D%95%E7%9A%84%E5%85%B3%E8%81%94%E6%8E%A7%E5%88%B6)
