### ISSUE TITLE
react-admin-kit项目无法启动

### ISSUE THREAD

**Issue by xiumubai** [jaykou25/react-admin-kit#24]
node版本：18
依赖安装：yarn
运行：yarn dev
分支：master
报错信息：[cause]: Error: jsx is a string value; tsconfig JSON must be parsed with parseJsonSourceFileConfigFileContent or getParsedCommandLineOfConfigFile before passing to createProgram

**Comment by jaykou25** [comment]
有截图吗

**Comment by xiumubai** [comment]
![image](https://github.com/user-attachments/assets/06923691-076a-47c7-a0a7-bf9d5d556a5d)

**Comment by jaykou25** [comment]
恩, 看到了, 是文档解析插件报错了, 把 .dumi.rc 14行的 jsx 先注掉就可以了. 
<img width="478" alt="Snipaste_2024-08-20_17-48-12" src="https://github.com/user-attachments/assets/da3d1a4a-5fe6-4f2d-94f7-69004d297e2a">

**Comment by xiumubai** [comment]
注释掉就可以了
